
-- Create proficiency questions table
CREATE TABLE public.proficiency_questions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  section text NOT NULL,
  difficulty text NOT NULL,
  question text NOT NULL,
  passage text,
  options jsonb NOT NULL,
  correct_index int NOT NULL,
  sort_order int DEFAULT 0
);

ALTER TABLE public.proficiency_questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view proficiency questions" ON public.proficiency_questions FOR SELECT USING (true);
CREATE POLICY "Admins can manage proficiency questions" ON public.proficiency_questions FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin'::app_role));

-- Seed 15 Grammar Questions
INSERT INTO public.proficiency_questions (section, difficulty, question, options, correct_index, sort_order) VALUES
('grammar','B2','If I ___ about the meeting, I would have attended.','["had known","knew","have known","would know"]',0,1),
('grammar','B2','The report ___ by the time you arrive tomorrow.','["will have been completed","will be completing","is completed","has been completed"]',0,2),
('grammar','B2','She suggested that he ___ a doctor immediately.','["see","sees","saw","would see"]',0,3),
('grammar','B2','Not until the rain stopped ___ leave the building.','["did we","we did","we","had we"]',0,4),
('grammar','B2','The children, ___ were playing outside, didn''t hear the bell.','["who","which","whom","whose"]',0,5),
('grammar','C1','Had the company invested earlier, they ___ such heavy losses.','["wouldn''t have suffered","wouldn''t suffer","didn''t suffer","haven''t suffered"]',0,6),
('grammar','C1','It is imperative that every student ___ the form before Friday.','["submit","submits","submitted","will submit"]',0,7),
('grammar','C1','Rarely ___ such a compelling argument in an academic paper.','["have I encountered","I have encountered","I encountered","did I encountered"]',0,8),
('grammar','C1','The project, the scope of ___ was never clearly defined, ultimately failed.','["which","that","what","whom"]',0,9),
('grammar','C1','___ his lack of experience, he managed to deliver an outstanding presentation.','["Notwithstanding","Although","Despite of","Irregardless of"]',0,10),
('grammar','C2','So complex was the equation that ___ the professor struggled to solve it.','["even","only","just","merely"]',0,11),
('grammar','C2','Were the government ___ the policy, the economic impact would be severe.','["to reverse","reversing","reversed","reverse"]',0,12),
('grammar','C2','The phenomenon, ___ implications are still being debated, has transformed the field.','["whose","which","of which","that"]',0,13),
('grammar','C2','Under no circumstances ___ to leave the premises during the examination.','["are candidates permitted","candidates are permitted","permitted are candidates","candidates permitted are"]',0,14),
('grammar','C2','By this time next year, she ___ on the project for over a decade.','["will have been working","will be working","will have worked","is going to work"]',0,15);

-- Seed 15 Vocabulary Questions
INSERT INTO public.proficiency_questions (section, difficulty, question, options, correct_index, sort_order) VALUES
('vocabulary','B2','The CEO decided to ___ the meeting until further notice.','["postpone","prevent","promote","perceive"]',0,16),
('vocabulary','B2','After months of negotiation, both parties reached a ___ agreement.','["mutual","common","shared","joined"]',0,17),
('vocabulary','B2','She has a ___ for languages; she speaks five fluently.','["knack","trick","skill","habit"]',0,18),
('vocabulary','B2','The new policy was met with widespread ___ from employees.','["resistance","persistence","existence","assistance"]',0,19),
('vocabulary','B2','His explanation was so ___ that everyone understood immediately.','["lucid","vivid","rigid","timid"]',0,20),
('vocabulary','C1','The diplomat spoke with remarkable ___, choosing every word carefully.','["circumspection","circumference","circumstance","circumvention"]',0,21),
('vocabulary','C1','The company''s profits have ___ declined over the past three quarters.','["steadily","readily","hardly","merely"]',0,22),
('vocabulary','C1','His ___ remarks during the meeting offended several colleagues.','["disparaging","discouraging","disappearing","disappointing"]',0,23),
('vocabulary','C1','The researcher''s findings ___ the prevailing theory in the field.','["corroborate","collaborate","deteriorate","elaborate"]',0,24),
('vocabulary','C1','To ___ means to speak about something at great length.','["expatiate","extricate","exonerate","extrapolate"]',0,25),
('vocabulary','C2','The professor''s lecture was so ___ that half the audience fell asleep.','["soporific","sporadic","sardonic","symbiotic"]',0,26),
('vocabulary','C2','Her ___ nature made her the perfect mediator for the dispute.','["equanimous","equivocal","ephemeral","ebullient"]',0,27),
('vocabulary','C2','The politician''s speech was full of ___ — it sounded impressive but said nothing.','["grandiloquence","magnanimity","benevolence","munificence"]',0,28),
('vocabulary','C2','The author''s writing style is known for its ___ — saying more with fewer words.','["brevity","levity","gravity","depravity"]',0,29),
('vocabulary','C2','The new regulations effectively ___ the previous exemptions.','["supersede","intercede","precede","concede"]',0,30);

-- Seed 10 Reading Comprehension Questions
INSERT INTO public.proficiency_questions (section, difficulty, question, passage, options, correct_index, sort_order) VALUES
('reading','C1','What is the main finding about chronic partial sleep restriction?','The relationship between sleep and cognitive performance has been the subject of extensive research over the past two decades. Studies consistently demonstrate that sleep deprivation impairs executive function, working memory, and attention. Particularly noteworthy is the finding that chronic partial sleep restriction — sleeping six hours or fewer per night — produces cognitive deficits comparable to total sleep deprivation of one to two days. Yet individuals subjected to chronic sleep restriction often fail to perceive their own declining performance, creating a dangerous disconnect between subjective alertness and objective capability. Recent neuroimaging studies have revealed that sleep deprivation preferentially affects the prefrontal cortex, the brain region most critical for complex decision-making and social behavior. This has significant implications for professions requiring sustained vigilance and sound judgment, including healthcare, aviation, and education.','["It produces effects similar to total sleep deprivation","It is less harmful than total sleep deprivation","It only affects physical performance","It primarily impacts emotional regulation"]',0,31),
('reading','C1','According to the passage, what is "dangerous" about chronic sleep restriction?','The relationship between sleep and cognitive performance has been the subject of extensive research over the past two decades. Studies consistently demonstrate that sleep deprivation impairs executive function, working memory, and attention. Particularly noteworthy is the finding that chronic partial sleep restriction — sleeping six hours or fewer per night — produces cognitive deficits comparable to total sleep deprivation of one to two days. Yet individuals subjected to chronic sleep restriction often fail to perceive their own declining performance, creating a dangerous disconnect between subjective alertness and objective capability. Recent neuroimaging studies have revealed that sleep deprivation preferentially affects the prefrontal cortex, the brain region most critical for complex decision-making and social behavior. This has significant implications for professions requiring sustained vigilance and sound judgment, including healthcare, aviation, and education.','["People don''t realize their performance is declining","It causes permanent brain damage","It leads to increased aggression","It cannot be reversed with rest"]',0,32),
('reading','C1','The word "preferentially" in the passage most likely means','The relationship between sleep and cognitive performance has been the subject of extensive research over the past two decades. Studies consistently demonstrate that sleep deprivation impairs executive function, working memory, and attention. Particularly noteworthy is the finding that chronic partial sleep restriction — sleeping six hours or fewer per night — produces cognitive deficits comparable to total sleep deprivation of one to two days. Yet individuals subjected to chronic sleep restriction often fail to perceive their own declining performance, creating a dangerous disconnect between subjective alertness and objective capability. Recent neuroimaging studies have revealed that sleep deprivation preferentially affects the prefrontal cortex, the brain region most critical for complex decision-making and social behavior. This has significant implications for professions requiring sustained vigilance and sound judgment, including healthcare, aviation, and education.','["more than other areas","randomly","temporarily","equally"]',0,33),
('reading','C1','Which professions does the passage specifically mention as being affected?','The relationship between sleep and cognitive performance has been the subject of extensive research over the past two decades. Studies consistently demonstrate that sleep deprivation impairs executive function, working memory, and attention. Particularly noteworthy is the finding that chronic partial sleep restriction — sleeping six hours or fewer per night — produces cognitive deficits comparable to total sleep deprivation of one to two days. Yet individuals subjected to chronic sleep restriction often fail to perceive their own declining performance, creating a dangerous disconnect between subjective alertness and objective capability. Recent neuroimaging studies have revealed that sleep deprivation preferentially affects the prefrontal cortex, the brain region most critical for complex decision-making and social behavior. This has significant implications for professions requiring sustained vigilance and sound judgment, including healthcare, aviation, and education.','["Healthcare, aviation, and education","Healthcare, law, and finance","Aviation, military, and engineering","Education, technology, and medicine"]',0,34),
('reading','C2','What can be inferred from the passage?','The relationship between sleep and cognitive performance has been the subject of extensive research over the past two decades. Studies consistently demonstrate that sleep deprivation impairs executive function, working memory, and attention. Particularly noteworthy is the finding that chronic partial sleep restriction — sleeping six hours or fewer per night — produces cognitive deficits comparable to total sleep deprivation of one to two days. Yet individuals subjected to chronic sleep restriction often fail to perceive their own declining performance, creating a dangerous disconnect between subjective alertness and objective capability. Recent neuroimaging studies have revealed that sleep deprivation preferentially affects the prefrontal cortex, the brain region most critical for complex decision-making and social behavior. This has significant implications for professions requiring sustained vigilance and sound judgment, including healthcare, aviation, and education.','["A teacher who sleeps 5 hours nightly may make poor decisions without realizing it","Sleep deprivation only matters for night-shift workers","Six hours of sleep is sufficient for most adults","Cognitive decline from sleep loss is immediately apparent"]',0,35),
('reading','C1','According to the passage, what percentage of the U.S. workforce participated in freelance work in 2024?','The gig economy has fundamentally transformed the traditional employer-employee relationship. In the United States alone, an estimated 59 million people participated in freelance work in 2024, representing approximately 36% of the workforce. This shift presents both opportunities and challenges. For workers, the gig economy offers unprecedented flexibility and autonomy; for companies, it provides access to specialized talent without long-term commitment. However, critics argue that this model transfers risk from corporations to individual workers, who often lack benefits such as health insurance, retirement plans, and paid leave. The classification of gig workers — whether they are independent contractors or employees — remains one of the most contentious legal questions of the decade. Several jurisdictions have enacted legislation attempting to clarify this distinction, with varying degrees of success. The ultimate resolution will likely require a fundamental rethinking of labor law frameworks that were designed for an era of stable, full-time employment.','["Approximately 36%","Approximately 59%","Approximately 25%","Approximately 50%"]',0,36),
('reading','C1','What is the main criticism of the gig economy mentioned in the passage?','The gig economy has fundamentally transformed the traditional employer-employee relationship. In the United States alone, an estimated 59 million people participated in freelance work in 2024, representing approximately 36% of the workforce. This shift presents both opportunities and challenges. For workers, the gig economy offers unprecedented flexibility and autonomy; for companies, it provides access to specialized talent without long-term commitment. However, critics argue that this model transfers risk from corporations to individual workers, who often lack benefits such as health insurance, retirement plans, and paid leave. The classification of gig workers — whether they are independent contractors or employees — remains one of the most contentious legal questions of the decade. Several jurisdictions have enacted legislation attempting to clarify this distinction, with varying degrees of success. The ultimate resolution will likely require a fundamental rethinking of labor law frameworks that were designed for an era of stable, full-time employment.','["Risk is transferred from companies to workers","Workers earn less than traditional employees","Companies cannot find reliable talent","Technology has made jobs obsolete"]',0,37),
('reading','C2','The word "contentious" in the passage most likely means','The gig economy has fundamentally transformed the traditional employer-employee relationship. In the United States alone, an estimated 59 million people participated in freelance work in 2024, representing approximately 36% of the workforce. This shift presents both opportunities and challenges. For workers, the gig economy offers unprecedented flexibility and autonomy; for companies, it provides access to specialized talent without long-term commitment. However, critics argue that this model transfers risk from corporations to individual workers, who often lack benefits such as health insurance, retirement plans, and paid leave. The classification of gig workers — whether they are independent contractors or employees — remains one of the most contentious legal questions of the decade. Several jurisdictions have enacted legislation attempting to clarify this distinction, with varying degrees of success. The ultimate resolution will likely require a fundamental rethinking of labor law frameworks that were designed for an era of stable, full-time employment.','["highly debated","easily resolved","widely accepted","rarely discussed"]',0,38),
('reading','C2','What does the passage suggest about current labor laws?','The gig economy has fundamentally transformed the traditional employer-employee relationship. In the United States alone, an estimated 59 million people participated in freelance work in 2024, representing approximately 36% of the workforce. This shift presents both opportunities and challenges. For workers, the gig economy offers unprecedented flexibility and autonomy; for companies, it provides access to specialized talent without long-term commitment. However, critics argue that this model transfers risk from corporations to individual workers, who often lack benefits such as health insurance, retirement plans, and paid leave. The classification of gig workers — whether they are independent contractors or employees — remains one of the most contentious legal questions of the decade. Several jurisdictions have enacted legislation attempting to clarify this distinction, with varying degrees of success. The ultimate resolution will likely require a fundamental rethinking of labor law frameworks that were designed for an era of stable, full-time employment.','["They were not designed for the modern gig economy","They adequately protect gig workers","They favor corporations over workers","They have been successfully updated"]',0,39),
('reading','C2','What can be inferred about the future of gig economy regulation?','The gig economy has fundamentally transformed the traditional employer-employee relationship. In the United States alone, an estimated 59 million people participated in freelance work in 2024, representing approximately 36% of the workforce. This shift presents both opportunities and challenges. For workers, the gig economy offers unprecedented flexibility and autonomy; for companies, it provides access to specialized talent without long-term commitment. However, critics argue that this model transfers risk from corporations to individual workers, who often lack benefits such as health insurance, retirement plans, and paid leave. The classification of gig workers — whether they are independent contractors or employees — remains one of the most contentious legal questions of the decade. Several jurisdictions have enacted legislation attempting to clarify this distinction, with varying degrees of success. The ultimate resolution will likely require a fundamental rethinking of labor law frameworks that were designed for an era of stable, full-time employment.','["Simple legislative fixes are unlikely to be sufficient","All gig workers will eventually be classified as employees","The gig economy will decline in coming years","Companies will voluntarily provide benefits"]',0,40);
